// Dev-only mock data — delete before production
import type { Profile } from '@/types'

const BASE: Omit<Profile, 'id' | 'user_id' | 'name' | 'age' | 'location' | 'gender' | 'sun_sign' | 'bio' | 'werte' | 'intention' | 'photos'> = {
  origin: null,
  orientation: 'Hetero',
  seeking: [],
  languages: ['Deutsch'],
  has_children: 'Keine',
  height_cm: 180,
  not_compatible_with: null,
  occupation: null,
  interests: [],
  bindungstyp: 'Sicher',
  love_language: 'Quality Time',
  love_language_secondary: null,
  introvert_extrovert: 50,
  spontan_strukturiert: 50,
  rational_emotional: 50,
  relationship_model: 'Monogamie',
  intention_text: null,
  sexual_interests: null,
  my_world: null,
  communities: null,
  sexuality_interests: null,
  sexuality_visible: false,
  hide_age: false,
  hide_location: false,
  profile_paused: false,
  profile_quote: null,
  birth_date: null,
  smoking: null,
  alcohol: null,
  prompts: [],
  dealbreakers: [],
  audio_prompt_url: null,
  ascendant: null,
  chinese_zodiac: null,
  is_complete: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  emotional_capacity: 'open',
  current_moment: null,
  daily_discover_count: 0,
  daily_discover_date: null,
  revisit_profiles: [],
  paused_since: null,
  onboarding_phase: 3,
  trial_started_at: null,
  trial_active: true,
  checkin_pattern: null,
  affirmations_enabled: false,
  affirmation_time: '08:00',
}

export const MOCK_LUKAS: Profile = {
  ...BASE,
  id: 'preview-lukas',
  user_id: 'preview-lukas-uid',
  name: 'Lukas',
  age: 34,
  location: 'Berlin',
  gender: 'Mann',
  sun_sign: 'Schütze',
  bio: 'Ich glaube, echte Nähe entsteht durch Verletzlichkeit. Direkt, neugierig und ich schätze Menschen, die wissen was sie wollen.',
  werte: ['Ehrlichkeit', 'Tiefe Verbindung', 'Natur', 'Wachstum'],
  intention: 'Tiefe Verbindung',
  photos: [],
  occupation: 'Architekt',
  profile_quote: 'Präsenz ist das größte Geschenk.',
}

export const MOCK_THOMAS: Profile = {
  ...BASE,
  id: 'preview-thomas',
  user_id: 'preview-thomas-uid',
  name: 'Thomas',
  age: 36,
  location: 'Hamburg',
  gender: 'Mann',
  sun_sign: 'Stier',
  bio: 'Ich nehme mir Zeit für echte Verbindungen. Kein Hetzen, kein Performen — einfach da sein.',
  werte: ['Verlässlichkeit', 'Humor', 'Verbindung'],
  intention: 'Bewusstes Miteinander',
  photos: [],
  occupation: 'Ingenieur',
}

export const MOCK_MICHAEL: Profile = {
  ...BASE,
  id: 'preview-michael',
  user_id: 'preview-michael-uid',
  name: 'Michael',
  age: 38,
  location: 'München',
  gender: 'Mann',
  sun_sign: 'Skorpion',
  bio: 'Tiefe Gespräche statt Small Talk. Ich bin neugierig auf das, was Menschen wirklich antreibt.',
  werte: ['Ehrlichkeit', 'Wachstum', 'Tiefe'],
  intention: 'Tiefe Verbindung',
  photos: [],
  occupation: 'Therapeut',
}

export const MOCK_VIEWER: Profile = {
  ...BASE,
  id: 'preview-viewer',
  user_id: 'preview-viewer-uid',
  name: 'Ich',
  age: 31,
  location: 'Berlin',
  gender: 'Frau',
  sun_sign: 'Waage',
  bio: null,
  werte: ['Ehrlichkeit', 'Achtsamkeit', 'Verbindung'],
  intention: 'Tiefe Verbindung',
  photos: [],
}
